#!/bin/zsh
cat <<EOF | ssh yagni -T
    source /usr/share/nvm/init-nvm.sh

    cd /home/arctair/microsoft-careers-scraper
    git fetch
    git reset origin/main --hard
    cd api
    nvm install
    npm install
    systemctl daemon-reload --user
    systemctl restart microsoft-careers-scraper --user
    journalctl -b --user --follow -u microsoft-careers-scraper
EOF
